version: "3.7"
services:

   inscripciones-back:
     image: promace-inscripciones
     #container_name: inscripciones-back
     restart: always
     ports:
       - "3000:3000"
     volumes:
       - ./backend_inscripciones:/app

   inscripciones-front:
     image: nginx:alpine
     #container_name: inscripciones-front
     restart: always
     ports:
       - "8081:80"
     volumes:
       - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./frontend_inscripciones/build:/usr/share/nginx/html
     command: [nginx-debug, '-g', 'daemon off;']

   inscripcione-db:
     image: postgres:10.3
     container_name: inscripciones-db
     restart: always
     restart: unless-stopped
     environment:
       POSTGRES_USER: ${USER_ROOT}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_USER: ${DB_USERNAME}
       POSTGRES_DB: ${DB_DATABASE}
       #APP_DB_USER: ${DB_USERNAME}
       #APP_DB_PASS: ${DB_PASSWORD}
       #APP_DB_NAME: ${DB_DATABASE}
       PGDATA: /var/lib/postgresql/data
     volumes:
       - ./db:/var/lib/postgresql/data
         # ports:
         # - "5432:5432"

